select
{{ add_surrograte_key("CUSTOMER_ID","CUSTOMER_NAME","EMAIL_ADDRESS") }} as CUSTOMER_SK,
CUST.CUSTOMER_ID,
CUST.CUSTOMER_NAME,
CUST.PHONE_NUMBER,
CUST.EMAIL_ADDRESS,
CUST.LOGIN_BY_USING,
CUST.GENDER,
CUST.DATE_OF_BIRTH,
CUST.ANNIVERSARY_DATE,
CUST.CUISINETYPES_PREF,
CUST.FOODTYPE_PREF,
CUST.DBT_VALID_FROM as EFF_START_DATE,
CUST.DBT_VALID_TO AS EFF_END_DATE,
{{ handle_is_current("DBT_VALID_TO") }} as IS_CURRENT
from {{ ref('customer_snapshot') }} CUST
