
select 
{{ add_surrograte_key ("ADDRESS_ID","CUSTOMER_ID","HOUSE_NO") }} as ADDRESS_SK,
ADDRESS_ID,
CUSTOMER_ID,
FLAT_NO,
HOUSE_NO,
FLOOR_NO,
BUILDING_NAME,
LANDMARK,
LOCALITY,
CITY,
STATE,
PINCODE,
LATITUDE,
LONGITUDE,
PRIMARY_FLAG,
ADDRESS_TYPE,
DBT_VALID_FROM AS EFF_START_DATE,
DBT_VALID_TO AS EFF_END_DATE,
{{ handle_is_current("DBT_VALID_TO") }} AS IS_CURRENT
from {{ ref('customer_address_snapshot') }}

